# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib gridwell, .registration = TRUE
NULL

#' Parse IR JSON into an external pointer.
#' @noRd
rs_parse_ir <- function(json) .Call(wrap__rs_parse_ir, json)

#' Validation errors (empty if valid).
#' @noRd
rs_validate <- function(table_ptr) .Call(wrap__rs_validate, table_ptr)

#' The table as JSON.
#' @noRd
rs_to_json <- function(table_ptr) .Call(wrap__rs_to_json, table_ptr)

#' Render to a text format through the registry (validates first).
#' @noRd
rs_render_text <- function(table_ptr, format, options) .Call(wrap__rs_render_text, table_ptr, format, options)

#' Render to a binary format through the registry (validates first).
#' @noRd
rs_render_binary <- function(table_ptr, format, options) .Call(wrap__rs_render_binary, table_ptr, format, options)

#' The registry as columns: name, description, kind, extension, media_type, and
#' options (each format's default options as a JSON string).
#' @noRd
rs_formats <- function() .Call(wrap__rs_formats)

# nolint end
