//! C FFI surface for gridwell.
//!
//! This crate exposes the gridwell table rendering pipeline through a C-compatible ABI.
//! It provides functions to parse IR JSON, validate tables, and render to all supported
//! output formats. The C header is `include/gridwell.h`, generated by cbindgen and
//! checked for drift by `tests/header.rs`.
//!
//! # Guarantees
//!
//! - **No unwinding across the boundary.** Every function that does real work runs
//!   inside `catch_unwind`; a Rust panic (always a gridwell bug) is reported as an
//!   error with code [`GRIDWELL_ERR_PANIC`] instead of unwinding into C, which would be
//!   undefined behavior (Rust < 1.81) or an abort (Rust ≥ 1.81).
//! - **Null-safe.** Null pointer arguments produce [`GRIDWELL_ERR_INVALID_ARG`]; the
//!   free functions accept null.
//! - **Owned buffers are boxed slices.** Results are allocated as `Box<[u8]>` with
//!   exactly the advertised length, so freeing them reconstructs the identical
//!   allocation.

use std::ffi::CStr;
use std::os::raw::c_char;
use std::panic::{self, AssertUnwindSafe};
use std::ptr;
use std::slice;

use gridwell_ir::Table;

// ─── Opaque types ───

/// Opaque handle to a parsed table.
pub struct GridwellTable {
    inner: Table,
}

/// Opaque error type.
pub struct GridwellError {
    /// NUL-terminated; contains no interior NULs.
    message: String,
    code: i32,
}

/// Result for text-format rendering.
///
/// On success `text` is a NUL-terminated UTF-8 string of `len` bytes (excluding the
/// terminator). On failure `text` is null and `len` is 0. Free with
/// `gridwell_free_text_result`.
#[repr(C)]
pub struct GridwellTextResult {
    pub text: *mut c_char,
    pub len: usize,
}

/// Result for binary-format rendering.
///
/// On success `data` points to `len` bytes. On failure `data` is null and `len` is 0.
/// Free with `gridwell_free_binary_result`.
#[repr(C)]
pub struct GridwellBinaryResult {
    pub data: *mut u8,
    pub len: usize,
}

// ─── Error codes ───

/// The IR could not be parsed (invalid UTF-8 or JSON, or wrong shape).
pub const GRIDWELL_ERR_PARSE: i32 = 1;
/// The IR parsed but failed validation; the message lists the errors.
pub const GRIDWELL_ERR_VALIDATE: i32 = 2;
/// A writer failed, or the format name is unknown.
pub const GRIDWELL_ERR_RENDER: i32 = 3;
/// A required pointer argument was null, or a string argument was not UTF-8.
pub const GRIDWELL_ERR_INVALID_ARG: i32 = 4;
/// An internal panic was caught at the boundary. This is always a gridwell bug.
pub const GRIDWELL_ERR_PANIC: i32 = 5;

// ─── Parsing ───

/// Parse an IR JSON string into a GridwellTable.
///
/// On success, returns a non-null pointer. On failure, returns null and
/// sets `*err` to a newly allocated error (if `err` is non-null).
///
/// # Safety
/// - `json` must be a valid pointer to `len` bytes of UTF-8 data.
/// - `err` may be null; if non-null, `*err` is written on failure.
#[no_mangle]
pub unsafe extern "C" fn gridwell_parse_ir(
    json: *const c_char,
    len: usize,
    err: *mut *mut GridwellError,
) -> *mut GridwellTable {
    guard(err, ptr::null_mut(), || {
        if json.is_null() {
            set_error(err, GRIDWELL_ERR_INVALID_ARG, "json pointer is null");
            return ptr::null_mut();
        }

        let json_bytes = unsafe { slice::from_raw_parts(json as *const u8, len) };
        let json_str = match std::str::from_utf8(json_bytes) {
            Ok(s) => s,
            Err(e) => {
                set_error(err, GRIDWELL_ERR_PARSE, &format!("invalid UTF-8: {e}"));
                return ptr::null_mut();
            }
        };

        match Table::from_json(json_str) {
            Ok(table) => Box::into_raw(Box::new(GridwellTable { inner: table })),
            Err(e) => {
                set_error(err, GRIDWELL_ERR_PARSE, &e.to_string());
                ptr::null_mut()
            }
        }
    })
}

// ─── Validation ───

/// Validate a parsed table. Returns null on success, or an error (code
/// `GRIDWELL_ERR_VALIDATE`) listing every validation error, separated by "; ".
///
/// # Safety
/// - `table` must be a valid pointer returned by `gridwell_parse_ir`.
#[no_mangle]
pub unsafe extern "C" fn gridwell_validate(table: *const GridwellTable) -> *mut GridwellError {
    let mut err = ptr::null_mut();
    let out = guard(&mut err, ptr::null_mut(), || {
        if table.is_null() {
            return make_error(GRIDWELL_ERR_INVALID_ARG, "table pointer is null");
        }

        let table = unsafe { &(*table).inner };
        let errors = table.validate();

        if errors.is_empty() {
            ptr::null_mut()
        } else {
            let messages: Vec<String> = errors.iter().map(|e| e.to_string()).collect();
            make_error(GRIDWELL_ERR_VALIDATE, &messages.join("; "))
        }
    });
    // A caught panic is reported through `err`; this function returns errors directly.
    if err.is_null() {
        out
    } else {
        err
    }
}

// ─── Text rendering ───

/// Render a table to a text format.
///
/// The table is validated first; invalid IR fails with `GRIDWELL_ERR_VALIDATE` and a
/// message listing the errors.
///
/// Supported formats: "html", "latex", "typst", "rtf", "svg", "ansi", "pandoc", "quarto".
///
/// # Safety
/// - `table` must be a valid pointer returned by `gridwell_parse_ir`.
/// - `format` must be a valid null-terminated C string.
/// - `err` may be null; if non-null, `*err` is written on failure.
#[no_mangle]
pub unsafe extern "C" fn gridwell_render_text(
    table: *const GridwellTable,
    format: *const c_char,
    err: *mut *mut GridwellError,
) -> GridwellTextResult {
    let empty = GridwellTextResult {
        text: ptr::null_mut(),
        len: 0,
    };
    guard(err, empty, || {
        let Some((table, format)) = (unsafe { render_args(table, format, err) }) else {
            return GridwellTextResult {
                text: ptr::null_mut(),
                len: 0,
            };
        };
        match render_text_format(table, format) {
            Ok(text) => {
                let len = text.len();
                let mut bytes = text.into_bytes();
                bytes.push(0);
                // Exactly len + 1 bytes; gridwell_free_text_result rebuilds this box.
                let text = Box::into_raw(bytes.into_boxed_slice()) as *mut c_char;
                GridwellTextResult { text, len }
            }
            Err(msg) => {
                set_error(err, GRIDWELL_ERR_RENDER, &msg);
                GridwellTextResult {
                    text: ptr::null_mut(),
                    len: 0,
                }
            }
        }
    })
}

// ─── Binary rendering ───

/// Render a table to a binary format.
///
/// The table is validated first; invalid IR fails with `GRIDWELL_ERR_VALIDATE` and a
/// message listing the errors.
///
/// Supported formats: "docx", "xlsx", "pptx".
///
/// # Safety
/// - `table` must be a valid pointer returned by `gridwell_parse_ir`.
/// - `format` must be a valid null-terminated C string.
/// - `err` may be null; if non-null, `*err` is written on failure.
#[no_mangle]
pub unsafe extern "C" fn gridwell_render_binary(
    table: *const GridwellTable,
    format: *const c_char,
    err: *mut *mut GridwellError,
) -> GridwellBinaryResult {
    let empty = GridwellBinaryResult {
        data: ptr::null_mut(),
        len: 0,
    };
    guard(err, empty, || {
        let failed = GridwellBinaryResult {
            data: ptr::null_mut(),
            len: 0,
        };
        let Some((table, format)) = (unsafe { render_args(table, format, err) }) else {
            return failed;
        };
        match render_binary_format(table, format) {
            Ok(bytes) if bytes.is_empty() => failed,
            Ok(bytes) => {
                let len = bytes.len();
                // Exactly len bytes; gridwell_free_binary_result rebuilds this box.
                let data = Box::into_raw(bytes.into_boxed_slice()) as *mut u8;
                GridwellBinaryResult { data, len }
            }
            Err(msg) => {
                set_error(err, GRIDWELL_ERR_RENDER, &msg);
                failed
            }
        }
    })
}

// ─── Memory management ───

/// Free a table returned by `gridwell_parse_ir`.
///
/// # Safety
/// - `table` must be a pointer returned by `gridwell_parse_ir`, or null, and must not
///   be used afterwards.
#[no_mangle]
pub unsafe extern "C" fn gridwell_free_table(table: *mut GridwellTable) {
    if !table.is_null() {
        drop(unsafe { Box::from_raw(table) });
    }
}

/// Free a text result returned by `gridwell_render_text`.
///
/// # Safety
/// - `result` must be a value returned by `gridwell_render_text` (unmodified), and
///   must not be freed twice.
#[no_mangle]
pub unsafe extern "C" fn gridwell_free_text_result(result: GridwellTextResult) {
    if !result.text.is_null() {
        // The allocation is a Box<[u8]> of len + 1 bytes (including the terminator).
        let slice = ptr::slice_from_raw_parts_mut(result.text as *mut u8, result.len + 1);
        drop(unsafe { Box::from_raw(slice) });
    }
}

/// Free a binary result returned by `gridwell_render_binary`.
///
/// # Safety
/// - `result` must be a value returned by `gridwell_render_binary` (unmodified), and
///   must not be freed twice.
#[no_mangle]
pub unsafe extern "C" fn gridwell_free_binary_result(result: GridwellBinaryResult) {
    if !result.data.is_null() {
        let slice = ptr::slice_from_raw_parts_mut(result.data, result.len);
        drop(unsafe { Box::from_raw(slice) });
    }
}

/// Free an error returned by any gridwell function.
///
/// # Safety
/// - `err` must be a pointer returned by a gridwell function, or null, and must not be
///   used afterwards.
#[no_mangle]
pub unsafe extern "C" fn gridwell_free_error(err: *mut GridwellError) {
    if !err.is_null() {
        drop(unsafe { Box::from_raw(err) });
    }
}

// ─── Error inspection ───

/// Get the error message as a null-terminated UTF-8 C string.
/// The returned pointer is valid until `gridwell_free_error` is called.
///
/// # Safety
/// - `err` must be a valid pointer to a GridwellError, or null.
#[no_mangle]
pub unsafe extern "C" fn gridwell_error_message(err: *const GridwellError) -> *const c_char {
    if err.is_null() {
        return c"(null error)".as_ptr();
    }
    let err = unsafe { &*err };
    // `make_error` guarantees a trailing NUL and no interior NULs.
    err.message.as_ptr() as *const c_char
}

/// Get the error code (one of the `GRIDWELL_ERR_*` constants), or 0 if `err` is null.
///
/// # Safety
/// - `err` must be a valid pointer to a GridwellError, or null.
#[no_mangle]
pub unsafe extern "C" fn gridwell_error_code(err: *const GridwellError) -> i32 {
    if err.is_null() {
        return 0;
    }
    unsafe { &*err }.code
}

// ─── Internal helpers ───

/// Run `f`, converting a panic into a `GRIDWELL_ERR_PANIC` error and `fallback`.
fn guard<T>(err: *mut *mut GridwellError, fallback: T, f: impl FnOnce() -> T) -> T {
    match panic::catch_unwind(AssertUnwindSafe(f)) {
        Ok(value) => value,
        Err(payload) => {
            let detail = payload
                .downcast_ref::<&str>()
                .map(|s| s.to_string())
                .or_else(|| payload.downcast_ref::<String>().cloned())
                .unwrap_or_else(|| "non-string panic payload".to_string());
            set_error(
                err,
                GRIDWELL_ERR_PANIC,
                &format!("internal error (this is a gridwell bug, please report it): {detail}"),
            );
            fallback
        }
    }
}

/// Shared argument handling for the render functions: null checks, UTF-8 format name,
/// and validation. On failure `*err` is set and `None` returned.
///
/// # Safety
/// `table` and `format` must satisfy the render functions' safety contracts.
unsafe fn render_args<'a>(
    table: *const GridwellTable,
    format: *const c_char,
    err: *mut *mut GridwellError,
) -> Option<(&'a Table, &'a str)> {
    if table.is_null() {
        set_error(err, GRIDWELL_ERR_INVALID_ARG, "table pointer is null");
        return None;
    }
    if format.is_null() {
        set_error(err, GRIDWELL_ERR_INVALID_ARG, "format pointer is null");
        return None;
    }

    let table = unsafe { &(*table).inner };
    let format = match unsafe { CStr::from_ptr(format) }.to_str() {
        Ok(s) => s,
        Err(e) => {
            set_error(
                err,
                GRIDWELL_ERR_INVALID_ARG,
                &format!("invalid format string: {e}"),
            );
            return None;
        }
    };

    // Writers assume valid IR; refuse anything else.
    if let Err(invalid) = table.ensure_valid() {
        set_error(err, GRIDWELL_ERR_VALIDATE, &invalid.to_string());
        return None;
    }

    Some((table, format))
}

fn render_text_format(table: &Table, format: &str) -> Result<String, String> {
    match format {
        "html" => gridwell_writer_html::HtmlWriter::new()
            .render(table)
            .map_err(|e| e.to_string()),
        "latex" => gridwell_writer_latex::LatexWriter::new()
            .render(table)
            .map_err(|e| e.to_string()),
        "typst" => gridwell_writer_typst::TypstWriter::new()
            .render(table)
            .map_err(|e| e.to_string()),
        "rtf" => gridwell_writer_rtf::RtfWriter::new()
            .render(table)
            .map_err(|e| e.to_string()),
        "svg" => gridwell_writer_svg::SvgWriter::new()
            .render(table)
            .map_err(|e| e.to_string()),
        "ansi" => gridwell_writer_ansi::AnsiWriter::new()
            .render(table)
            .map_err(|e| e.to_string()),
        "pandoc" => gridwell_writer_pandoc::PandocWriter::new()
            .render(table)
            .map_err(|e| e.to_string()),
        "quarto" => gridwell_writer_quarto::QuartoWriter::new()
            .render(table)
            .map_err(|e| e.to_string()),
        // Unit tests only: exercise the panic guard end to end.
        #[cfg(test)]
        "__panic" => panic!("deliberate test panic"),
        _ => Err(format!("unknown text format: \"{format}\"")),
    }
}

fn render_binary_format(table: &Table, format: &str) -> Result<Vec<u8>, String> {
    match format {
        "docx" => gridwell_writer_docx::DocxWriter::new()
            .render(table)
            .map_err(|e| e.to_string()),
        "xlsx" => gridwell_writer_xlsx::XlsxWriter::new()
            .render(table)
            .map_err(|e| e.to_string()),
        "pptx" => gridwell_writer_pptx::PptxWriter::new()
            .render(table)
            .map_err(|e| e.to_string()),
        #[cfg(test)]
        "__panic" => std::panic::panic_any(String::from("deliberate test panic (String)")),
        _ => Err(format!("unknown binary format: \"{format}\"")),
    }
}

fn set_error(err: *mut *mut GridwellError, code: i32, message: &str) {
    if !err.is_null() {
        unsafe { *err = make_error(code, message) };
    }
}

fn make_error(code: i32, message: &str) -> *mut GridwellError {
    // Interior NULs would silently truncate the C string; make them visible instead.
    let mut msg = message.replace('\0', "\\0");
    msg.push('\0');
    Box::into_raw(Box::new(GridwellError { message: msg, code }))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::CString;

    const MINIMAL: &str = r#"{
        "ir_version": "1.0",
        "config": { "table_cols": 1, "header_rows": 0, "body_rows": 1 },
        "styles": { "defs": {}, "compositions": {}, "conditionals": [] },
        "column_spec": [{ "id": "a" }],
        "table": { "thead": { "rows": [] },
                   "tbody": [{ "rows": [{ "cells": [{ "content": [] }] }] }] }
    }"#;

    fn parse(json: &str) -> *mut GridwellTable {
        let mut err = ptr::null_mut();
        let t = unsafe { gridwell_parse_ir(json.as_ptr() as *const c_char, json.len(), &mut err) };
        assert!(!t.is_null() && err.is_null());
        t
    }

    fn message(err: *const GridwellError) -> String {
        unsafe { CStr::from_ptr(gridwell_error_message(err)) }
            .to_str()
            .unwrap()
            .to_owned()
    }

    #[test]
    fn panic_in_text_writer_becomes_panic_error() {
        let t = parse(MINIMAL);
        let fmt = CString::new("__panic").unwrap();
        let mut err = ptr::null_mut();
        let r = unsafe { gridwell_render_text(t, fmt.as_ptr(), &mut err) };
        assert!(r.text.is_null() && r.len == 0);
        assert_eq!(unsafe { gridwell_error_code(err) }, GRIDWELL_ERR_PANIC);
        let msg = message(err);
        assert!(
            msg.contains("gridwell bug") && msg.contains("deliberate test panic"),
            "{msg}"
        );
        unsafe {
            gridwell_free_error(err);
            gridwell_free_table(t);
        }
    }

    #[test]
    fn panic_with_string_payload_is_reported() {
        let t = parse(MINIMAL);
        let fmt = CString::new("__panic").unwrap();
        let mut err = ptr::null_mut();
        let r = unsafe { gridwell_render_binary(t, fmt.as_ptr(), &mut err) };
        assert!(r.data.is_null() && r.len == 0);
        assert_eq!(unsafe { gridwell_error_code(err) }, GRIDWELL_ERR_PANIC);
        assert!(message(err).contains("(String)"), "{}", message(err));
        unsafe {
            gridwell_free_error(err);
            gridwell_free_table(t);
        }
    }

    #[test]
    fn panic_with_null_err_pointer_is_swallowed_safely() {
        let t = parse(MINIMAL);
        let fmt = CString::new("__panic").unwrap();
        let r = unsafe { gridwell_render_text(t, fmt.as_ptr(), ptr::null_mut()) };
        assert!(r.text.is_null());
        unsafe { gridwell_free_table(t) };
    }

    #[test]
    fn guard_reports_non_string_payloads() {
        let mut err = ptr::null_mut();
        let v = guard(&mut err, 7, || std::panic::panic_any(42_u8));
        assert_eq!(v, 7);
        assert_eq!(unsafe { gridwell_error_code(err) }, GRIDWELL_ERR_PANIC);
        assert!(message(err).contains("non-string panic payload"));
        unsafe { gridwell_free_error(err) };
    }

    #[test]
    fn guard_passes_through_values_without_touching_err() {
        let mut err = ptr::null_mut();
        assert_eq!(guard(&mut err, 0, || 5), 5);
        assert!(err.is_null());
    }

    #[test]
    fn interior_nul_in_message_is_escaped_not_truncating() {
        let err = make_error(GRIDWELL_ERR_RENDER, "before\0after");
        assert_eq!(message(err), "before\\0after");
        unsafe { gridwell_free_error(err) };
    }

    #[test]
    fn text_result_is_exactly_len_plus_nul() {
        let t = parse(MINIMAL);
        let fmt = CString::new("html").unwrap();
        let mut err = ptr::null_mut();
        let r = unsafe { gridwell_render_text(t, fmt.as_ptr(), &mut err) };
        assert!(err.is_null());
        let s = unsafe { CStr::from_ptr(r.text) };
        assert_eq!(s.to_bytes().len(), r.len);
        unsafe {
            gridwell_free_text_result(r);
            gridwell_free_table(t);
        }
    }
}
