/*
 * gridwell C API.
 *
 * Generated by cbindgen from crates/gridwell-ffi/src/lib.rs. Do not edit by hand:
 * edit the Rust source and run
 *     GRIDWELL_BLESS=1 cargo test -p gridwell-ffi --test header
 */

#ifndef GRIDWELL_H
#define GRIDWELL_H

#include <stddef.h>
#include <stdint.h>

// The IR could not be parsed (invalid UTF-8 or JSON, or wrong shape).
#define GRIDWELL_ERR_PARSE 1

// The IR parsed but failed validation; the message lists the errors.
#define GRIDWELL_ERR_VALIDATE 2

// A writer failed, the format name is unknown, or a text format was passed to a
// binary render function (or vice versa).
#define GRIDWELL_ERR_RENDER 3

// A required pointer argument was null, or a string argument was not UTF-8.
#define GRIDWELL_ERR_INVALID_ARG 4

// An internal panic was caught at the boundary. This is always a gridwell bug.
#define GRIDWELL_ERR_PANIC 5

// The writer options are not valid: malformed JSON, not an object, an unknown
// field, a wrong type, or a value out of range. The message says which.
#define GRIDWELL_ERR_OPTIONS 6

// `gridwell_format_kind`: no format has this name.
#define GRIDWELL_FORMAT_UNKNOWN 0

// `gridwell_format_kind`: a text format (render with `gridwell_render_text`).
#define GRIDWELL_FORMAT_TEXT 1

// `gridwell_format_kind`: a binary format (render with `gridwell_render_binary`).
#define GRIDWELL_FORMAT_BINARY 2

// Opaque error type.
typedef struct GridwellError GridwellError;

// Opaque handle to a parsed table.
typedef struct GridwellTable GridwellTable;

// Result for text-format rendering.
//
// On success `text` is a NUL-terminated UTF-8 string of `len` bytes (excluding the
// terminator). On failure `text` is null and `len` is 0. Free with
// `gridwell_free_text_result`.
typedef struct GridwellTextResult {
  char *text;
  size_t len;
} GridwellTextResult;

// Result for binary-format rendering.
//
// On success `data` points to `len` bytes. On failure `data` is null and `len` is 0.
// Free with `gridwell_free_binary_result`.
typedef struct GridwellBinaryResult {
  uint8_t *data;
  size_t len;
} GridwellBinaryResult;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Parse an IR JSON string into a GridwellTable.
//
// On success, returns a non-null pointer. On failure, returns null and
// sets `*err` to a newly allocated error (if `err` is non-null).
//
// # Safety
// - `json` must be a valid pointer to `len` bytes of UTF-8 data.
// - `err` may be null; if non-null, `*err` is written on failure.
struct GridwellTable *gridwell_parse_ir(const char *json, size_t len, struct GridwellError **err);

// Validate a parsed table. Returns null on success, or an error (code
// `GRIDWELL_ERR_VALIDATE`) listing every validation error, separated by "; ".
//
// # Safety
// - `table` must be a valid pointer returned by `gridwell_parse_ir`.
struct GridwellError *gridwell_validate(const struct GridwellTable *table);

// Render a table to a text format with default options. Same as
// `gridwell_render_text_with_options` with null options.
//
// # Safety
// See `gridwell_render_text_with_options`.
struct GridwellTextResult gridwell_render_text(const struct GridwellTable *table,
                                               const char *format,
                                               struct GridwellError **err);

// Render a table to a text format.
//
// `format` is a name from `gridwell_format_names()` (case-insensitive) whose kind
// is `GRIDWELL_FORMAT_TEXT`. `options` is a JSON object of writer options, or null
// (or empty) for the defaults; see the docs for each format's options.
//
// The table is validated first; invalid IR fails with `GRIDWELL_ERR_VALIDATE` and a
// message listing the errors. Bad options fail with `GRIDWELL_ERR_OPTIONS`; an
// unknown or binary format with `GRIDWELL_ERR_RENDER`.
//
// # Safety
// - `table` must be a valid pointer returned by `gridwell_parse_ir`.
// - `format` must be a valid null-terminated C string.
// - `options` must be null or a valid null-terminated C string.
// - `err` may be null; if non-null, `*err` is written on failure.
struct GridwellTextResult gridwell_render_text_with_options(const struct GridwellTable *table,
                                                            const char *format,
                                                            const char *options,
                                                            struct GridwellError **err);

// Render a table to a binary format with default options. Same as
// `gridwell_render_binary_with_options` with null options.
//
// # Safety
// See `gridwell_render_binary_with_options`.
struct GridwellBinaryResult gridwell_render_binary(const struct GridwellTable *table,
                                                   const char *format,
                                                   struct GridwellError **err);

// Render a table to a binary format (`GRIDWELL_FORMAT_BINARY`: "docx", "xlsx",
// "pptx").
//
// Validation, options and errors are as for `gridwell_render_text_with_options`.
//
// # Safety
// - `table` must be a valid pointer returned by `gridwell_parse_ir`.
// - `format` must be a valid null-terminated C string.
// - `options` must be null or a valid null-terminated C string.
// - `err` may be null; if non-null, `*err` is written on failure.
struct GridwellBinaryResult gridwell_render_binary_with_options(const struct GridwellTable *table,
                                                                const char *format,
                                                                const char *options,
                                                                struct GridwellError **err);

// The supported format names, comma-separated (e.g. "html,latex,…,pptx"). The
// string is static: do not free it.
const char *gridwell_format_names(void);

// The kind of a format: `GRIDWELL_FORMAT_TEXT`, `GRIDWELL_FORMAT_BINARY`, or
// `GRIDWELL_FORMAT_UNKNOWN` (also for a null or non-UTF-8 name).
//
// # Safety
// - `format` must be null or a valid null-terminated C string.
int32_t gridwell_format_kind(const char *format);

// Free a table returned by `gridwell_parse_ir`.
//
// # Safety
// - `table` must be a pointer returned by `gridwell_parse_ir`, or null, and must not
//   be used afterwards.
void gridwell_free_table(struct GridwellTable *table);

// Free a text result returned by `gridwell_render_text`.
//
// # Safety
// - `result` must be a value returned by `gridwell_render_text` (unmodified), and
//   must not be freed twice.
void gridwell_free_text_result(struct GridwellTextResult result);

// Free a binary result returned by `gridwell_render_binary`.
//
// # Safety
// - `result` must be a value returned by `gridwell_render_binary` (unmodified), and
//   must not be freed twice.
void gridwell_free_binary_result(struct GridwellBinaryResult result);

// Free an error returned by any gridwell function.
//
// # Safety
// - `err` must be a pointer returned by a gridwell function, or null, and must not be
//   used afterwards.
void gridwell_free_error(struct GridwellError *err);

// Get the error message as a null-terminated UTF-8 C string.
// The returned pointer is valid until `gridwell_free_error` is called.
//
// # Safety
// - `err` must be a valid pointer to a GridwellError, or null.
const char *gridwell_error_message(const struct GridwellError *err);

// Get the error code (one of the `GRIDWELL_ERR_*` constants), or 0 if `err` is null.
//
// # Safety
// - `err` must be a valid pointer to a GridwellError, or null.
int32_t gridwell_error_code(const struct GridwellError *err);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* GRIDWELL_H */
